'use strict';

// Integration regression test (spec §10): run the entry scripts as child processes through spawnSync in a temporary Git repo or a non-Git directory,
// feed stdin, and assert (exit/stdout/stderr) to pin the behaviour contract after the crash fix.
// Covers deferred PostToolUse recording + unified Stop processing scenarios a-e + pre_commit denyTool/passSilent.

const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { resolvePython } = require('../lib/python');

const postEdit = path.join(__dirname, '..', 'post_edit.js');
const stopCheck = path.join(__dirname, '..', 'stop_check.js');
const preCommit = path.join(__dirname, '..', 'pre_commit.js');
const BOM = Buffer.from([0xEF, 0xBB, 0xBF]);

function sh(args, cwd) { spawnSync('git', args, { cwd, stdio: 'pipe' }); }

// Isolate HOME so the real global template is not read (the hard-coded default incremental config is used)
const fakeHome = fs.mkdtempSync(path.join(os.tmpdir(), 'cse-inthome-'));
const env = {
  ...process.env,
  HOME: fakeHome,
  USERPROFILE: fakeHome,
  CLAUDE_PLUGIN_DATA: path.join(fakeHome, 'plugin-data'),
};

const repos = [];
function newDirectory(prefix) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), prefix || 'cse-int-'));
  repos.push(tmp);
  return tmp;
}

function newRepo(prefix) {
  const tmp = newDirectory(prefix);
  sh(['init'], tmp);
  sh(['config', 'user.email', 't@t.com'], tmp);
  sh(['config', 'user.name', 't'], tmp);
  sh(['config', 'commit.gpgsign', 'false'], tmp);
  return tmp;
}

function configureCpplintOnly(root) {
  const cfgDir = path.join(root, '.claude-cpp-style');
  fs.mkdirSync(cfgDir, { recursive: true });
  fs.writeFileSync(path.join(cfgDir, 'cpp-style.json'), JSON.stringify({
    checks: { clangFormat: false, cpplint: true, bom: false },
  }));
}

function writeHeader(filePath, guard) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `#ifndef ${guard}\n#define ${guard}\n\n#endif  // ${guard}\n`);
}

let turnCounter = 0;
function runDeferred(input) {
  turnCounter += 1;
  const hookInput = {
    session_id: `integration-session-${turnCounter}`,
    tool_use_id: `tool-${turnCounter}`,
    ...input,
  };
  const cwd = input.cwd || process.cwd();
  const post = spawnSync('node', [postEdit], {
    input: JSON.stringify(hookInput), encoding: 'utf-8', timeout: 30000, env, cwd,
  });
  const stop = spawnSync('node', [stopCheck], {
    input: JSON.stringify({
      session_id: hookInput.session_id,
      cwd,
      hook_event_name: 'Stop',
      stop_hook_active: false,
    }),
    encoding: 'utf-8', timeout: 30000, env, cwd,
  });
  return { post, stop };
}

function runPost(input) {
  return spawnSync('node', [postEdit], {
    input: JSON.stringify(input), encoding: 'utf-8', timeout: 30000, env,
  });
}

function runPreCommit(input, cwd) {
  return spawnSync('node', [preCommit], {
    input: JSON.stringify(input), encoding: 'utf-8', timeout: 30000, env, cwd,
  });
}

const hasPython = resolvePython() !== null;

try {
  // ---- Scenario (a): a tracked file keeps its original encoding, BOM and body ----
  {
    const repo = newRepo('cse-a-');
    const f = path.join(repo, 'old.cpp');
    const originalBytes = Buffer.from('int  old_var( ){return 0;}\n', 'utf8');
    fs.writeFileSync(f, originalBytes);
    sh(['add', 'old.cpp'], repo);
    sh(['commit', '-m', 'init'], repo);

    const { post, stop } = runDeferred({ cwd: repo, tool_name: 'Edit', tool_input: { file_path: f } });
    assert.strictEqual(post.status, 0, 'scenario a: editing an old file exits 0 (no crash)');
    assert.strictEqual((post.stdout || '').trim(), '', 'scenario a: the edit phase only records and never blocks');
    assert.strictEqual(stop.status, 0, 'scenario a: unified Stop processing exits 0');
    assert.strictEqual((stop.stdout || '').trim(), '', 'scenario a: Stop ends silently when the bytes are unchanged');
    assert.ok(fs.readFileSync(f).equals(originalBytes), 'scenario a: the old file keeps its encoding, BOM and body');
  }

  // A config generated by an older version may still contain legacyChecks.bom:true; it must not rewrite tracked files either.
  {
    const repo = newRepo('cse-a-legacy-config-');
    const cfgDir = path.join(repo, '.claude-cpp-style');
    fs.mkdirSync(cfgDir, { recursive: true });
    fs.writeFileSync(path.join(cfgDir, 'cpp-style.json'), JSON.stringify({
      mode: 'incremental',
      legacyChecks: { bom: true },
    }));
    const f = path.join(repo, 'legacy-config.cpp');
    const originalBytes = Buffer.from('int legacy_config;\n', 'utf8');
    fs.writeFileSync(f, originalBytes);
    sh(['add', 'legacy-config.cpp'], repo);
    sh(['commit', '-m', 'init'], repo);

    const { stop } = runDeferred({ cwd: repo, tool_name: 'Edit', tool_input: { file_path: f } });
    assert.strictEqual((stop.stdout || '').trim(), '', 'an old BOM config must not trigger a rewrite of an old file');
    assert.ok(fs.readFileSync(f).equals(originalBytes), 'the original BOM state is kept under the old config');
  }

  // ---- Scenario (c): an explicit restatement of the same contract as (a) (old files keep their encoding) ----
  // Already covered by scenario a; no second repo is created.

  // ---- Scenario (d): enabled:false -> complete no-op (exit 0 with no output, zero bytes changed) ----
  {
    const repo = newRepo('cse-d-');
    const cfgDir = path.join(repo, '.claude-cpp-style');
    fs.mkdirSync(cfgDir, { recursive: true });
    fs.writeFileSync(path.join(cfgDir, 'cpp-style.json'), JSON.stringify({ enabled: false }));
    const f = path.join(repo, 'noop.cpp');
    // New file + messy formatting + no BOM: enabled:false must not change a single byte
    fs.writeFileSync(f, 'int  main( ){int x=1;return x;}\n');
    const before = fs.readFileSync(f);

    const { post, stop } = runDeferred({ cwd: repo, tool_name: 'Write', tool_input: { file_path: f } });
    assert.strictEqual(post.status, 0, 'scenario d: enabled:false exits 0');
    assert.strictEqual((post.stdout || '').trim(), '', 'scenario d: stdout is empty in the edit phase');
    assert.strictEqual((stop.stdout || '').trim(), '', 'scenario d: Stop is a no-op');
    assert.ok(fs.readFileSync(f).equals(before), 'scenario d: enabled:false leaves the file byte-identical');
  }

  // ---- Scenario (e): a mistaken Bash payload (no file_path) -> passSilent; also verify single-process (no child node chain) ----
  {
    const repo = newRepo('cse-e-');
    const start = Date.now();
    const r = runPost({ cwd: repo, tool_name: 'Bash', tool_input: { command: 'echo "edit a.cpp"' } });
    const elapsed = Date.now() - start;
    assert.strictEqual(r.status, 0, 'scenario e: a mistaken Bash payload exits 0');
    assert.strictEqual((r.stdout || '').trim(), '', 'scenario e: no file_path -> passSilent with empty stdout');
    // Single-process pipeline: at most spawns git/python/clang-format, never a child node. Total time stays reasonable.
    assert.ok(elapsed < 30000, 'scenario e: the single-process pipeline finishes in reasonable time (<30s)');
  }
  // Static check: the post_edit.js entry does not spawn a node child process (no child node chain)
  {
    const srcPost = fs.readFileSync(postEdit, 'utf-8');
    assert.ok(!/spawn[A-Za-z]*\(\s*['"]node['"]/.test(srcPost),
      'scenario e: post_edit.js does not spawn a node child process (single-process pipeline)');
  }

  // A C-style cast triggers the cpplint readability/casting violation; clang-format does not fix it,
  // so after the full pipeline (clang-format -> ... -> cpplint) the violation remains -> block/deny is guaranteed.
  // (Do not use long lines or tight braces: clang-format would split the line / add spaces and remove the violation.)
  const VIOLATION_CPP = 'int main() {\n  double d = 3.5;\n  int y = (int)d;\n  return y;\n}\n';

  // ---- Scenario (b): new file + cpplint violation -> exit 0 + stdout contains a decision:block JSON (needs python + cpplint) ----
  if (hasPython) {
    const repo = newRepo('cse-b-');
    const f = path.join(repo, 'new.cpp');
    // Untracked new file -> incremental runs the full set
    fs.writeFileSync(f, VIOLATION_CPP);

    const { post, stop } = runDeferred({ cwd: repo, tool_name: 'Write', tool_input: { file_path: f } });
    assert.strictEqual(post.status, 0, 'scenario b: the edit phase exits 0');
    assert.strictEqual((post.stdout || '').trim(), '', 'scenario b: the edit phase neither checks nor blocks');
    assert.strictEqual(stop.status, 0, 'scenario b: the Stop check exits 0 (never exit 2)');
    const stdout = (stop.stdout || '').trim();
    assert.ok(stdout.length > 0, 'scenario b: Stop must produce stdout (block) when it finds a violation');
    const parsed = JSON.parse(stdout);
    assert.strictEqual(parsed.decision, 'block', 'scenario b: a violation in a new file -> decision:block JSON');
    assert.ok(typeof parsed.reason === 'string' && parsed.reason.length > 0, 'scenario b: reason is non-empty');
    assert.ok(/casting/.test(parsed.reason), 'scenario b: reason mentions the readability/casting violation');
  }

  // Project without Git: the real Stop derives a stable guard from the task directory and rejects a machine-absolute-path guard.
  if (hasPython) {
    const workspace = newDirectory('cse-no-git-guard-');
    configureCpplintOnly(workspace);
    const f = path.join(workspace, 'work_cpp_smoke', 'batch_collector.h');
    const guard = 'WORK_CPP_SMOKE_BATCH_COLLECTOR_H_';
    writeHeader(f, guard);
    const originalBytes = fs.readFileSync(f);

    const { post, stop } = runDeferred({ cwd: workspace, tool_name: 'Write', tool_input: { file_path: f } });
    assert.strictEqual(post.status, 0, 'no-Git guard: PostToolUse exits 0');
    assert.strictEqual((post.stdout || '').trim(), '', 'no-Git guard: the edit phase only records');
    assert.strictEqual(stop.status, 0, 'no-Git guard: Stop exits 0');
    assert.strictEqual((stop.stdout || '').trim(), '', 'no-Git guard: the project-relative guard passes');
    assert.ok(fs.readFileSync(f).equals(originalBytes), 'no-Git guard: the check does not rewrite the header');

    const absoluteGuard = f.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase() + '_';
    writeHeader(f, absoluteGuard);
    const { stop: invalidStop } = runDeferred({
      cwd: workspace, tool_name: 'Edit', tool_input: { file_path: f },
    });
    assert.strictEqual(invalidStop.status, 0, 'absolute-path guard: Stop exits 0');
    const invalid = JSON.parse(invalidStop.stdout);
    assert.strictEqual(invalid.decision, 'block', 'absolute-path guard: must be rejected');
    assert.ok(invalid.reason.includes('[build/header_guard]'), 'absolute-path guard: the guard check is kept');
    assert.ok(invalid.reason.includes(`please use: ${guard}`), 'absolute-path guard: suggests the stable project-relative macro name');

    // cwd and the file directory share a name prefix but neither contains the other, so it must fall back to the file's own directory.
    const cwd = path.join(workspace, 'project');
    fs.mkdirSync(cwd);
    const external = path.join(workspace, 'project-other', 'include', 'batch_collector.h');
    writeHeader(external, 'BATCH_COLLECTOR_H_');
    const { stop: externalStop } = runDeferred({
      cwd, tool_name: 'Write', tool_input: { file_path: external },
    });
    assert.strictEqual(externalStop.status, 0, 'same-prefix directories: Stop exits 0');
    assert.strictEqual((externalStop.stdout || '').trim(), '',
      'same-prefix directories: cwd is not treated as the containing root; the guard uses the file directory');
  }

  // The Git root wins over the task cwd: editing a header from a subdirectory still uses the repository-relative guard.
  if (hasPython) {
    const repo = newRepo('cse-git-guard-');
    configureCpplintOnly(repo);
    const f = path.join(repo, 'work_cpp_smoke', 'batch_collector.h');
    writeHeader(f, 'WORK_CPP_SMOKE_BATCH_COLLECTOR_H_');
    const { stop } = runDeferred({
      cwd: path.dirname(f), tool_name: 'Write', tool_input: { file_path: f },
    });
    assert.strictEqual(stop.status, 0, 'Git guard: Stop exit 0');
    assert.strictEqual((stop.stdout || '').trim(), '', 'Git guard: the real Git root wins over cwd');
  }

  // ---- pre_commit integration: a staged .cpp with violations + a real git commit command -> denyTool (exit 0 + permissionDecision:deny) ----
  // Note: under incremental, a file after `git add` counts as tracked for git ls-files (isNew=false) and is filtered out,
  // so mode:full makes pre_commit run cpplint on every staged C++ file and exercises the deny path reliably.
  if (hasPython) {
    const repo = newRepo('cse-pc-deny-');
    const cfgDir = path.join(repo, '.claude-cpp-style');
    fs.mkdirSync(cfgDir, { recursive: true });
    fs.writeFileSync(path.join(cfgDir, 'cpp-style.json'), JSON.stringify({ mode: 'full' }));
    const f = path.join(repo, 'bad.cpp');
    fs.writeFileSync(f, VIOLATION_CPP);  // Staged, with a violation
    sh(['add', 'bad.cpp'], repo);

    const r = runPreCommit(
      { cwd: repo, tool_name: 'Bash', tool_input: { command: 'git commit -m "x"' } }, repo);
    assert.strictEqual(r.status, 0, 'pre_commit: denyTool still exits 0');
    const stdout = (r.stdout || '').trim();
    assert.ok(stdout.length > 0, 'pre_commit: a staged violation must produce stdout (deny)');
    const parsed = JSON.parse(stdout);
    assert.strictEqual(parsed.hookSpecificOutput.permissionDecision, 'deny',
      'pre_commit: a staged .cpp with violations -> permissionDecision:deny');
    assert.ok(parsed.hookSpecificOutput.permissionDecisionReason.length > 0,
      'pre_commit: the deny reason is non-empty');
  }

  // ---- pre_commit integration: no staged C++ -> passSilent (exit 0, empty stdout) ----
  {
    const repo = newRepo('cse-pc-pass-');
    const txt = path.join(repo, 'readme.txt');
    fs.writeFileSync(txt, 'hello');
    sh(['add', 'readme.txt'], repo);  // A staged non-C++ file

    const r = runPreCommit(
      { cwd: repo, tool_name: 'Bash', tool_input: { command: 'git commit -m "x"' } }, repo);
    assert.strictEqual(r.status, 0, 'pre_commit: no staged C++ exits 0');
    assert.strictEqual((r.stdout || '').trim(), '', 'pre_commit: no staged C++ -> passSilent with empty stdout');
  }

  // ---- pre_commit integration: a non-commit command -> passSilent ----
  {
    const repo = newRepo('cse-pc-nc-');
    const r = runPreCommit(
      { cwd: repo, tool_name: 'Bash', tool_input: { command: 'git status' } }, repo);
    assert.strictEqual(r.status, 0, 'pre_commit: a non-commit command exits 0');
    assert.strictEqual((r.stdout || '').trim(), '', 'pre_commit: a non-commit command -> passSilent with empty stdout');
  }

  console.log('integration.test.js PASS');
} finally {
  for (const r of repos) {
    try { fs.rmSync(r, { recursive: true, force: true }); } catch (_) {}
  }
  try { fs.rmSync(fakeHome, { recursive: true, force: true }); } catch (_) {}
}
