'use strict';

const fs = require('fs');
const path = require('path');
const { userTemplatePath, DEFAULT_CONFIG } = require('./config.js');

const README_CONTENT = `cpp-style-enforcer project configuration
=========================================
Config file:     .claude-cpp-style/cpp-style.json
Global template: ~/.claude/cpp-style-template.json (the base every project inherits from;
                 editing it affects all projects)

-----------------------------------------------------------
Fields
-----------------------------------------------------------

enabled (boolean, default true)
  Turns the plugin on or off. Set to false to disable all processing without deleting the file.
  Example: disable the plugin -> "enabled": false

mode (string, default "incremental")
  How new and old files are treated.
  "incremental" - new files (not in git HEAD) get the full \`checks\`; tracked files only get \`legacyChecks\`.
  "full"        - every file gets the full \`checks\` and \`legacyChecks\` is ignored; tracked files still
                  keep their original BOM state.
  Example: force the full set on every file -> "mode": "full"

checks (object)
  Switches applied to new files (not in git HEAD) or when mode=full.
  checks.clangFormat (boolean, default true) - format the whole file with clang-format.
  checks.cpplint     (boolean, default true) - run cpplint (Google C++ style); violations make Claude
                                               fix them before the round ends.
  checks.bom         (boolean, default true) - ensure new files have a UTF-8 BOM; tracked files are left alone.
  Example: skip cpplint for new files -> "checks": { "cpplint": false }

legacyChecks (object)
  Switches applied to tracked files (in git HEAD) when mode=incremental. Everything is off by default.
  legacyChecks.clangFormat (boolean, default false) - format old files (changed lines only).
  legacyChecks.cpplint     (boolean, default false) - run cpplint on old files.
  legacyChecks.bom         (boolean, default false) - kept for compatibility; old files always keep their BOM state.
  Example: lint old files too -> "legacyChecks": { "cpplint": true }

lineEnding (string, default "preserve")
  Edited C/C++ files in a Visual Studio source project are forced to CRLF, including files that were
  wrongly converted to LF. Other projects can choose "lf", "crlf" or "preserve"; preserve keeps the
  majority line ending of the body (ties go to the first one, no line ending means LF).
  A non-empty file without a final newline gets the same kind of newline, independent of
  clang-format and of legacyChecks.
  The nearest CMakeLists.txt wins over an outer VS marker, and VS files generated by CMake are not
  treated as native VS projects. When a directory has both build entry points it is treated as
  CMake; set "lineEnding": "crlf" explicitly if you need CRLF.
  Only files edited in this round are repaired; encoding and BOM are preserved and the Git index
  is never touched. enabled=false turns everything off.

Removed settings
  The copyright-header feature was removed. "copyright" / "copyrightInfo" keys in old config files
  are ignored.

-----------------------------------------------------------
When processing happens
-----------------------------------------------------------
Edits are only recorded. When the round ends (Stop, or SubagentStop for a subagent) the plugin runs
clang-format -> BOM -> line endings -> cpplint on the recorded files and asks Claude to review the
final diff when something was rewritten or a violation remains.

-----------------------------------------------------------
Common scenarios
-----------------------------------------------------------

Scenario 1: old project, old files keep their format, new files get the full set (the default)
  {
    "mode": "incremental",
    "legacyChecks": { "clangFormat": false, "cpplint": false, "bom": false }
  }

Scenario 2: old project, run the full set on every file including old ones
  {
    "mode": "full"
  }

Scenario 3: old project, lint old files but do not format them
  {
    "mode": "incremental",
    "legacyChecks": { "clangFormat": false, "cpplint": true, "bom": false }
  }

Scenario 4: new project, turn cpplint off (the project is not compliant yet)
  {
    "checks": { "cpplint": false }
  }

Scenario 5: temporarily disable the whole plugin
  {
    "enabled": false
  }

-----------------------------------------------------------
Editing the global template
-----------------------------------------------------------
Global template path: ~/.claude/cpp-style-template.json (Windows: C:\\Users\\<you>\\.claude\\cpp-style-template.json)
After you edit it, every project without its own project-level config inherits the new values.
Fields in a project-level cpp-style.json (the file next to this README) win over the global template.
`;

/**
 * Append \`.claude-cpp-style/\` to the project's root .gitignore (idempotent: nothing is written
 * when the entry already exists). Creates the file when missing; write failures are swallowed.
 * @param {string} root Git repository root.
 * @example
 * ensureGitignore('/proj') // .gitignore now contains ".claude-cpp-style/"
 */
function ensureGitignore(root) {
  try {
    const gitignorePath = path.join(root, '.gitignore');
    const entry = '.claude-cpp-style/';
    let existing = '';
    try {
      existing = fs.readFileSync(gitignorePath, 'utf-8');
    } catch (_) {
      // The file does not exist: keep the empty string and write it below.
    }
    // Already contains .claude-cpp-style or .claude-cpp-style/ -> do not write again.
    if (/^\.claude-cpp-style\/?$/m.test(existing)) return;
    const suffix = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
    fs.appendFileSync(gitignorePath, `${suffix}${entry}\n`, 'utf-8');
  } catch (_) {
    // A write failure must not affect the main flow.
  }
}

/**
 * When the full set runs and the project root has no \`.claude-cpp-style/cpp-style.json\`, copy the
 * global template there. Also writes README.txt explaining each field (never overwritten) and makes
 * sure .gitignore contains \`.claude-cpp-style/\` without depending on any external hook.
 *
 * - root is null (not a git repo) -> nothing is generated (there is no reliable project root).
 * - root/.claude-cpp-style/cpp-style.json exists -> never overwritten.
 * - Content comes from ~/.claude/cpp-style-template.json; missing or corrupt -> the hard-coded default schema.
 * - Files are written as UTF-8 without BOM and with LF; failures are swallowed.
 *
 * @param {string|null} root Git repository root.
 * @param {string} [templatePath] Global template path (default \`~/.claude/cpp-style-template.json\`).
 * @example
 * ensureProjectConfig('/proj') // creates /proj/.claude-cpp-style/cpp-style.json on first use
 */
function ensureProjectConfig(root, templatePath = userTemplatePath()) {
  if (!root) return;
  try {
    const dir = path.join(root, '.claude-cpp-style');
    const target = path.join(dir, 'cpp-style.json');
    const readme = path.join(dir, 'README.txt');

    fs.mkdirSync(dir, { recursive: true });

    // JSON config: never overwrite an existing one.
    if (!fs.existsSync(target)) {
      let content = null;
      try {
        if (templatePath && fs.existsSync(templatePath)) {
          const raw = fs.readFileSync(templatePath, 'utf-8');
          JSON.parse(raw); // Validate; a corrupt template falls back to the defaults.
          content = raw;
        }
      } catch (_) {
        content = null;
      }
      if (content === null) {
        content = JSON.stringify(DEFAULT_CONFIG, null, 2) + '\n';
      }
      fs.writeFileSync(target, Buffer.from(content, 'utf-8'));
    }

    // README.txt: never overwrite an existing one.
    if (!fs.existsSync(readme)) {
      fs.writeFileSync(readme, Buffer.from(README_CONTENT, 'utf-8'));
    }
  } catch (_) {
    // Generation failures must not affect the main flow.
  }

  // Self-sufficient: make sure .gitignore contains .claude-cpp-style/ without relying on a hook.
  ensureGitignore(root);
}

module.exports = { ensureProjectConfig };
