'use strict';

const fs = require('fs');
const path = require('path');

const CONTENT = `# Generated by cpp-style-enforcer — Google C++ Style
BasedOnStyle: Google
IndentWidth: 2
NamespaceIndentation: None
`;

/**
 * When the full set runs and the project root has no .clang-format, generate a Google-style one.
 * VS, clangd and this plugin then all read the same config, so the style stays consistent.
 *
 * - root is null (not a git repo) -> nothing is generated (no reliable project root).
 * - .clang-format or _clang-format (the Windows-compatible name) already exists -> never overwritten, return immediately.
 * - Files are written as UTF-8 without BOM and with LF; failures are swallowed with try/catch.
 *
 * @param {string|null} root Git repository root.
 */
function ensureClangFormatConfig(root) {
  if (!root) return;
  try {
    // clang-format inherits config from parent directories; do not create a root config that would shadow a style that already applies.
    let current = path.resolve(root);
    while (true) {
      if (fs.existsSync(path.join(current, '.clang-format'))
          || fs.existsSync(path.join(current, '_clang-format'))) return;
      const parent = path.dirname(current);
      if (parent === current) break;
      current = parent;
    }
    fs.writeFileSync(path.join(root, '.clang-format'), Buffer.from(CONTENT, 'utf-8'), { flag: 'wx' });
  } catch (_) {
    // A generation failure must not affect the main flow.
  }
}

module.exports = { ensureClangFormatConfig };
