'use strict';

const path = require('path');

/** Extensions of C / C++ source files (headers included) */
const CPP_EXTENSIONS = new Set(['.c', '.cc', '.cpp', '.cxx', '.h', '.hpp', '.hxx']);

/** Directory names to skip (third-party / build output / package managers) */
const EXCLUDED_DIRS = new Set([
  'node_modules', 'build', 'dist', 'out', 'bin', 'obj',
  '.git', 'target', 'third_party', 'thirdparty', 'external',
  'vendor', 'deps', 'packages',
  '3rd', '3rdparty', '3rd_party', '3rd-party',
  'thirdpart', 'third-party', 'third_part', 'third-part',
  'thridpart', 'thridparty', 'thrid_party', 'thrid-party',
]);

/** Specific file names to skip (generated by VS / must not be restyled) */
const SKIPPED_FILES = new Set(['resource.h', 'targetver.h', 'stdafx.h', 'pch.h']);

const PATH_KEYS = new Set([
  'file_path', 'filePath', 'path', 'relative_path', 'relativePath',
  'target_path', 'targetPath',
]);
const PATCH_KEYS = new Set(['patch', 'diff']);

/**
 * Extract the target files from Agentic Patch / apply-patch style text.
 * Supports `*** Update File:`, the rename target `*** Move to:`, and unified-diff `+++ b/...` headers.
 * @param {string} patchText
 * @returns {string[]}
 */
function patchPaths(patchText) {
  if (typeof patchText !== 'string') return [];
  const result = [];
  const patterns = [
    /^\*\*\* (?:(?:Add|Update|Delete) File|Move to):\s*(.+?)\s*$/gm,
    /^\+\+\+\s+(?:b\/)?(.+?)\s*$/gm,
  ];
  for (const pattern of patterns) {
    for (const match of patchText.matchAll(pattern)) {
      const value = match[1].trim();
      if (value && value !== '/dev/null') result.push(value);
    }
  }
  return result;
}

/**
 * Extract every file path from the arguments of a built-in edit tool or an MCP batch patch.
 * Only explicit path fields and patch headers are recognized; ordinary source content is never treated as a path.
 * @param {object} input
 * @returns {string[]}
 */
function resolveFilePaths(input) {
  if (!input || typeof input !== 'object') return [];
  const cwd = input.cwd || process.cwd();
  const paths = [];
  const add = (value) => {
    if (typeof value !== 'string' || !value.trim()) return;
    const file = value.trim();
    paths.push(path.isAbsolute(file) ? file : path.resolve(cwd, file));
  };
  const visit = (value, key = '') => {
    if (typeof value === 'string') {
      if (PATH_KEYS.has(key)) add(value);
      if (PATCH_KEYS.has(key)) patchPaths(value).forEach(add);
      return;
    }
    if (Array.isArray(value)) {
      value.forEach((item) => visit(item, key));
      return;
    }
    if (!value || typeof value !== 'object') return;
    for (const [childKey, childValue] of Object.entries(value)) {
      visit(childValue, childKey);
    }
  };

  if (typeof input.tool_input === 'string') add(input.tool_input);
  else visit(input.tool_input || null);
  for (const key of PATH_KEYS) {
    if (Object.prototype.hasOwnProperty.call(input, key)) add(input[key]);
  }
  const seen = new Set();
  return paths.filter((file) => {
    const key = file.replace(/\\/g, '/').toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * Extract the edited file path from the hook stdin JSON (Write/Edit/MultiEdit/NotebookEdit/MCP).
 * Bash commands are not handled (the Bash matcher was removed from PostToolUse).
 * Always returns an absolute path: a relative path is resolved against input.cwd (provided by the hook protocol; Claude Code normally passes an absolute file_path)
 * so a relative path is not passed through as-is, which would misplace repoRoot, config lookup and .clang-format generation.
 * @param {object} input
 * @returns {string|null}
 */
function resolveFilePath(input) {
  if (input && typeof input.tool_input === 'string') {
    const cwd = input.cwd || process.cwd();
    return path.isAbsolute(input.tool_input)
      ? input.tool_input
      : path.resolve(cwd, input.tool_input);
  }
  return resolveFilePaths(input)[0] || null;
}

/**
 * Whether the file should be handled: extension matches && not in SKIPPED_FILES && no EXCLUDED_DIRS in the path.
 * @param {string} filePath
 * @returns {boolean}
 */
function shouldHandle(filePath) {
  if (!filePath || typeof filePath !== 'string') return false;
  const ext = path.extname(filePath).toLowerCase();
  if (!CPP_EXTENSIONS.has(ext)) return false;
  if (SKIPPED_FILES.has(path.basename(filePath).toLowerCase())) return false;
  return !isExcludedPath(filePath);
}

/**
 * Match excluded directories by whole path segment; the file name itself is ignored, and a business directory that merely contains vendor/thirdparty as a substring is not excluded.
 * @param {string} filePath
 * @returns {boolean}
 * @example
 * isExcludedPath('/p/3rdparty/zlib/zlib.h') // true
 * isExcludedPath('/p/src/vendor_api.cpp')  // false
 */
function isExcludedPath(filePath) {
  return typeof filePath === 'string' && filePath.split(/[/\\]/).slice(0, -1)
    .some((part) => EXCLUDED_DIRS.has(part.toLowerCase()));
}

module.exports = {
  resolveFilePath,
  resolveFilePaths,
  shouldHandle,
  isExcludedPath,
  CPP_EXTENSIONS,
  EXCLUDED_DIRS,
  SKIPPED_FILES,
};
